dist: trusty
sudo: required
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - lcov
      - clang-5.0



compiler:
  - gcc
  - clang

matrix:
  include:
  - compiler: gcc
    env: COVERAGE="-c"
  - compiler: gcc
    env: SCAN="-s"
  - compiler: gcc
    env: COVERAGE="-c" SCAN="-s"

before_install:
  - pip install --user cpp-coveralls
  - sudo apt install clang-5.0

install:
  - mkdir -p build/unit
  - cd build/unit

script:
  - ../../scripts/build.sh $COVERAGE $SCAN 
  - cd ../..
  - ls -al $TRAVIS_BUILD_DIR/artifacts/*/*

after_success:
- |
  if [ -n "$COVERAGE" ]; then
    coveralls --verbose --root . -e external
    bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  fi


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: artifacts/results/*
  verbose: true
