dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
  - clang


#sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - lcov
      - clang-5.0

before_install:
  - pip install --user cpp-coveralls
  - sudo apt install clang-5.0

install:
#  - gcov --version
#  - g++ --version
  - ls -al /usr/share/clang
  - scan-build -h
  - mkdir -p build/unit
  - cd build/unit
  - cmake -DCMAKE_BUILD_TYPE=UnitTest -DCOVERAGE=ON -DCOV_OUTPUT=ON ../..

script:
- |
  make socket && \
  make unit_TCP && \
  ./unit_TCP --gtest_output="xml" && \
  cat test_detail.xml && \
  make coverage_runner && \
  cd ../..

after_success:
  - pwd
  - coveralls --verbose --root . -e external
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"