dist: trusty
sudo: required
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - lcov
      - clang-5.0

branches:
  only:
    - master



compiler:
  - gcc
  - clang

matrix:
  include:
  - compiler: gcc
    env: COVERAGE="-c"
  - compiler: gcc
    env: SCAN="-s"
  - compiler: gcc
    env: COVERAGE="-c" SCAN="-s"

before_install:
  - pip install --user cpp-coveralls
  - sudo apt install clang-5.0

install:
  - mkdir -p build/unit
  - cd build/unit

script:
  - ../../scripts/build.sh $COVERAGE $SCAN 
  - cd ../.. #back to root dir
  - ls -al $TRAVIS_BUILD_DIR/artifacts/*/* #check how build artifact structure looks like

after_success:
- |
  if [ -n "$COVERAGE" ]; then # only try to push to cov-sites if cov is available
    coveralls --verbose --root . -e external
    bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  fi
  if [ -n "$COVERAGE" ] && [ -n "$SCAN" ]; then
    ./scripts/deploy.sh travis-push
  fi



  #git fetch origin
  #git branch -v -a
  #git checkout -b stage_page origin/stage_page
  #../../scripts/deploy.sh Test

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  local-dir: artifacts/results/
#  on:
#    branch: master  
#  verbose: true
